namespace AppoinmentSchelulingProject;

public abstract class AppoinmentSchelulingProjectApplicationTestBase : AppoinmentSchelulingProjectTestBase<AppoinmentSchelulingProjectApplicationTestModule>
{

}
