using Volo.Abp;

namespace AppoinmentSchelulingProject.EntityFrameworkCore;

public abstract class AppoinmentSchelulingProjectEntityFrameworkCoreTestBase : AppoinmentSchelulingProjectTestBase<AppoinmentSchelulingProjectEntityFrameworkCoreTestModule>
{

}
